### ISSUE TITLE
TIME_FIRST and TIME_LAST

### ISSUE THREAD

**Issue by tonglingxiangyu** [koumajos/Classification_by_NetTiSA_flow#1]
Hello author, how do TIME_FIRST and TIME_LAST in the dataset come from?

**Comment by koumajos** [comment]
Hello, TIME_FIRST is the timestamp of the first packet in the IP flow, and TIME_LAST is the timestamp of the last packet in the IP flow. Furthermore, the IP flows in this dataset are created by sampling the connections with an inactive timeout of 60 seconds and an active timeout of 300 seconds (this setting is based on the setting of IP flow exporter Ipfixprobe https://github.com/CESNET/ipfixprobe ).

**Comment by tonglingxiangyu** [comment]
> Hello, TIME_FIRST is the timestamp of the first packet in the IP flow, and TIME_LAST is the timestamp of the last packet in the IP flow. Furthermore, the IP flows in this dataset are created by sampling the connections with an inactive timeout of 60 seconds and an active timeout of 300 seconds (this setting is based on the setting of IP flow exporter Ipfixprobe https://github.com/CESNET/ipfixprobe ).

I know, I mean how does this field come from? For example, there is no such field in the ISCX-Tor-2016 dataset. How do you get the TIME_FIRST and TIME_LAST fields? In addition, can you provide the code for calculating the third type of features?

**Comment by koumajos** [comment]
In the ISCX-Tor-2016 dataset are PCAP files containing timestamps of capturing packets. Therefore, the IP flow exporter uses these timestamps to define TIME_FIRST and TIME_LAST.

The code for the computation of the third set of features is pretty simple. In Python, for example:

```
def compute_third_set_of_features(df):
    # Min minus Max: Difference between minimum and maximum payload lengths
    df['MIN_MINUS_MAX'] = df['MAX'] - df['MIN']

    # Percent deviation: Dispersion of the average absolute difference to the mean value
    df['PERCENT_DEVIATION'] = (df['AVERAGE_DISPERSION'] / df['MEAN']).fillna(0)

    # Variance: Spread measure of the data from its mean
    df['VAR'] = df['STDEV'] ** 2

    # Burstiness: Degree of peakedness in the central part of the distribution
    df['BURSTINESS'] = ((df['STDEV'] - df['MEAN']) / (df['STDEV'] + df['MEAN'])).fillna(0)

    # Coefficient of variation: Dimensionless quantity comparing dispersion to the mean value
    df['COEFFICIENT_OF_VARIATION'] = (df['STDEV'] / df['MEAN']).fillna(0)

    # Directions: Percentage ratio of packet directions
    df['DIRECTIONS'] = (df['PACKETS'] / (df['PACKETS'] + df['PACKETS_REV'])).fillna(0)

    # Duration: Duration of the flow
    df['DURATION'] = df['TIME_LAST'] - df['TIME_FIRST']

    return df
    ```

**Comment by tonglingxiangyu** [comment]
> In the ISCX-Tor-2016 dataset are PCAP files containing timestamps of capturing packets. Therefore, the IP flow exporter uses these timestamps to define TIME_FIRST and TIME_LAST.
> 
> The code for the computation of the third set of features is pretty simple. In Python, for example:
> 
> ```
> def compute_third_set_of_features(df):
>     # Min minus Max: Difference between minimum and maximum payload lengths
>     df['MIN_MINUS_MAX'] = df['MAX'] - df['MIN']
> 
>     # Percent deviation: Dispersion of the average absolute difference to the mean value
>     df['PERCENT_DEVIATION'] = (df['AVERAGE_DISPERSION'] / df['MEAN']).fillna(0)
> 
>     # Variance: Spread measure of the data from its mean
>     df['VAR'] = df['STDEV'] ** 2
> 
>     # Burstiness: Degree of peakedness in the central part of the distribution
>     df['BURSTINESS'] = ((df['STDEV'] - df['MEAN']) / (df['STDEV'] + df['MEAN'])).fillna(0)
> 
>     # Coefficient of variation: Dimensionless quantity comparing dispersion to the mean value
>     df['COEFFICIENT_OF_VARIATION'] = (df['STDEV'] / df['MEAN']).fillna(0)
> 
>     # Directions: Percentage ratio of packet directions
>     df['DIRECTIONS'] = (df['PACKETS'] / (df['PACKETS'] + df['PACKETS_REV'])).fillna(0)
> 
>     # Duration: Duration of the flow
>     df['DURATION'] = df['TIME_LAST'] - df['TIME_FIRST']
> 
>     return df
>     ```
> ```

Thanks a lot!
