### ISSUE TITLE
the label of the time series

### ISSUE THREAD

**Issue by tonglingxiangyu** [koumajos/Classification_by_NetTiSA_flow#3]
If there are multiple types of traffic in a time series, which category should the label of this time series belong to?

**Comment by koumajos** [comment]
It cannot be multiple traffic types in a time series, because time series are created from packets inside one IP flow.

**Comment by tonglingxiangyu** [comment]
Are the IP flow labels derived from ipfixprobe or are they labeled by yourself?

**Comment by koumajos** [comment]
Labels were assigned based on descriptions from original datasets.

**Comment by tonglingxiangyu** [comment]
> Labels were assigned based on descriptions from original datasets.

Thanks for your reply.
